// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Emoji = require("./emoji.bs.js");
var React = require("react");
var ProgressiveEmoji = require("./progressiveEmoji.bs.js");

function App(Props) {
  var emojis = Emoji.getPeople(undefined).map(function (emoji) {
        return React.createElement(ProgressiveEmoji.make, {
                    emoji: emoji
                  });
      });
  return React.createElement("div", {
              className: "app"
            }, React.createElement("h1", {
                  className: "header"
                }, "Together"), emojis);
}

var make = App;

exports.make = make;
/* Emoji Not a pure module */
