// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./app.bs.js");
var React = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/legacy/ReactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement(App.make, {}), "root");

/*  Not a pure module */
