// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./app.bs.js");
var React = require("react");
var ReactDom = require("react-dom");

var e = document.querySelector("#root");

if (!(e == null)) {
  ReactDom.render(React.createElement(App.make, {}), e);
}

/* e Not a pure module */
