// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Emoji = require("./emoji.bs.js");
var React = require("react");
var Twemoji = require("twemoji");

function getTwemojiSource(emoji) {
  var codePoint = Twemoji.convert.toCodePoint(emoji);
  return "https://twemoji.maxcdn.com/2/svg/" + (codePoint + ".svg");
}

function ProgressiveEmoji(Props) {
  var emoji = Props.emoji;
  var initialState_src = getTwemojiSource(emoji);
  var initialState = {
    loaded: false,
    src: initialState_src
  };
  var match = React.useState(function () {
        return initialState;
      });
  var setState = match[1];
  var state = match[0];
  var people = Emoji.getPeople(undefined);
  var emojis = people.map(function (emoji) {
        return React.createElement("img", {
                    className: "emoji",
                    src: emoji
                  });
      });
  React.useEffect((function () {
          var image = new Image();
          image.onload = (function (param) {
              return Curry._1(setState, (function (state) {
                            return {
                                    loaded: true,
                                    src: state.src
                                  };
                          }));
            });
          image.src = state.src;
          
        }), [
        state,
        setState
      ]);
  return React.createElement("div", {
              className: "app"
            }, React.createElement("h1", {
                  className: "header"
                }, "Together"), emojis);
}

var make = ProgressiveEmoji;

exports.getTwemojiSource = getTwemojiSource;
exports.make = make;
/* Emoji Not a pure module */
